
/*
    Author: alganthe
    This file is where all the enemies and objects are going to be defined (the ones from the missions / SM) at least.
    Please keep the format of the defines as is, if a define is an array keep it an array.
*/

//------------------------------------ Main AO

// Vehicles
#define MRAPList ["rhsgref_BRDM2_ATGM_vdv","rhsgref_BRDM2UM_vdv"]
#define AAVehicleList ["RHS_Ural_Zu23_VDV_01","rhs_zsu234_aa"]
#define RandomVehicleList ["rhs_btr80a_vdv","rhs_btr80_vdv","rhs_btr70_vdv","rhs_btr60_vdv","rhs_bmp2_vdv","rhs_bmp2e_vdv","rhs_bmp2d_vdv","rhs_bmp2k_vdv","rhs_sprut_vdv"]

// Urban groups related stuff
#define UrbanGroupsCFGPATH >> "CfgGroups" >> "East" >> "OPF_F" >> "UInfantry" >>
#define UrbanGroupsList ["rhs_vdv_des_at","rhs_vdv_des_arifleman","rhs_vdv_des_efreitor","rhs_vdv_des_junior_sergeant","rhs_vdv_des_rifleman","rhs_vdv_des_rifleman_asval","rhs_vdv_des_grenadier","rhs_vdv_des_LAT","rhs_vdv_des_RShG2","rhs_vdv_des_grenadier_rpg","rhs_vdv_des_medic","rhs_vdv_des_machinegunner","rhs_vdv_des_engineer","rhs_vdv_des_aa","rhs_vdv_des_marksman"]
#define UrbanUnits []

// Infantry groups related stuff
#define InfantryGroupsCFGPATH >> "CfgGroups" >> "East" >> "OPF_T_F" >> "Infantry" >>
#define InfantryGroupList ["rhs_group_rus_vdv_infantry_section_mg","rhs_group_rus_vdv_infantry_squad","rhs_group_rus_vdv_infantry_squad_2mg","rhs_group_rus_vdv_infantry_squad_mg_sniper","rhs_group_rus_vdv_infantry_squad_sniper"]
#define AAGroupsList ["rhs_group_rus_vdv_infantry_section_AA"]
#define ATGroupsList ["rhs_group_rus_vdv_infantry_section_AT"]

// Buildings that are always going to be filled when present in the AO
#define MilitaryBuildings ["Land_Cargo_House_V1_F", "Land_Cargo_House_V2_F", "Land_Cargo_House_V3_F", "Land_Cargo_House_V4_F", "Land_Medevac_house_V1_F", "Land_Research_house_V1_F", "Land_Cargo_HQ_V1_F", "Land_Cargo_HQ_V2_F", "Land_Cargo_HQ_V3_F", "Land_Cargo_HQ_V4_F", "Land_Research_HQ_F", "Land_Medevac_HQ_V1_F", "Land_Cargo_Patrol_V1_F", "Land_Cargo_Patrol_V2_F", "Land_Cargo_Patrol_V3_F", "Land_Cargo_Patrol_V3_F", "Land_Cargo_Tower_V1_F", "Land_Cargo_Tower_V2_F", "Land_Cargo_Tower_V3_F", "Land_Cargo_Tower_V4_F", "Land_i_Barracks_V1_F","Land_Barracks_01_dilapidated_F", "Land_Barracks_01_grey_F", "Land_i_Barracks_V2_F", "Land_PillboxBunker_01_big_F", "Land_PillboxBunker_01_hex_F", "Land_PillboxBunker_01_rectangle_F"]

//------------------------------------ Random stuff
#define AirReinforcementVehicleList ["RHS_Mi8mt_vdv"]
